### ISSUE TITLE
Some ulf-type-string? issues

### ISSUE THREAD

**Issue by bkane2** [genelkim/ulf-lib#5]
```
(ulf-lib::ulf-type-string? '(the.d (n+preds man.n (under.p (the.d bridge.n)))))
=>
"{((D=>(S=>2))_N=>D)|((D=>(S=>2))_P=>D)}"
```

```
(ulf-lib::ulf-type-string? '(the.d (big.a man.n)))
=>
"{((D=>(S=>2))_N=>D)|((D=>(S=>2))_P=>D)}"
```

```
(ulf-lib::ulf-type-string? '(a.d (melting.n pot.n)))
=>
"{((D=>(S=>2))_N=>D)|((D=>(S=>2))_P=>D)}"
```

Noun phrases with modifiers seem to give this type (which is also equivalent to `(ulf-lib::ulf-type-string? 'the.d)`), where it should be type D.

```
(ulf-lib::ulf-type-string? '(that (|Mary| (past run.v))))
=>
NIL
```

The sentence reifier 'that' applied to a sentence gives NIL type, whereas I think it should be type D.

```
(ulf-lib::ulf-type-string? '(np+preds |John| (on.p (the.d bridge.n))))
=>
"(S=>2)"
```

**Comment by genelkim** [comment]
I believe Mandar hasn't implemented any of the macros yet and assumes that type-relaxing preprocessing has been completed (e.g. automatic insertion of `mod-n` and `mod-a`: `(melting.n pot.n)` -> `((mod-n melting.n) pot.n)`.

The last issue with `that` is definitely a bug though. That should be fixed as soon as possible.

**Comment by genelkim** [comment]
I'm going through old issues now and it seems most of these are fixed now (and probably have been for a while).

```
* (ulf-lib::ulf-type-string? '(the.d (n+preds man.n (under.p (the.d bridge.n)))))

"D"
```

```
* (ulf-lib::ulf-type-string? '(the.d ((mod-n big.a) man.n)))

"D"
```

```
* (ulf-lib::ulf-type-string? '(a.d ((mod-n melting.n) pot.n)))

"D"
```

```
* (ulf-lib::ulf-type-string? '(that (|Mary| (past run.v))))

"D"
```

```
* (ulf-lib::ulf-type-string? '(np+preds |John| (on.p (the.d bridge.n))))

"{+PREDS[NP+[D]]|D}"
```

But for some reason, now we don't get nil when a `mod-n` isn't supplied when it should be.
```
* (ulf-lib::ulf-type-string? '(the.d (big.a man.n)))

"{((D=>(S=>2))_N=>D)%LEX|((D=>(S=>2))_P=>D)%LEX}"
```
```
* (ulf-lib::ulf-type-string? '(a.d (melting.n pot.n)))

"{((D=>(S=>2))_N=>D)%LEX|((D=>(S=>2))_P=>D)%LEX}"
```
Note that this is the same type as the determiner in general.
```
* (ulf-lib::ulf-type-string? 'a.d)

"{((D=>(S=>2))_N=>D)%LEX|((D=>(S=>2))_P=>D)%LEX}"
```

**Comment by genelkim** [comment]
Fixed https://github.com/genelkim/ulf-lib/pull/51
